DROP ROLE IF EXISTS nmadauss;
CREATE ROLE nmadauss WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'fady_mist_traumas_phthaleins';
	
ALTER DATABASE dnagb OWNER TO nmadauss;